site_name: Stuart Haresnape
site_url: https://stuartharesnape.com

theme:
  name: material
  palette:
    scheme: slate
  features:
    - navigation.tabs

markdown_extensions:
  - tables

extra_css:
  - stylesheets/extra.css

nav:
  - Home: index.md
  - Investments:
      - Overview: investments/index.md
      - Boringdon Villas: investments/boringdon-villas/index.md