site_name: Stuart Haresnape
site_url: https://stuartharesnape.com

theme:
  name: material
  palette:
    scheme: slate
  features:
    - navigation.tabs

markdown_extensions:
  - tables

extra_css:
  - stylesheets/extra.css
  - https://cdn.jsdelivr.net/npm/glightbox/dist/css/glightbox.min.css

extra_javascript:
  - https://cdn.jsdelivr.net/npm/glightbox/dist/js/glightbox.min.js
  - javascripts/gallery.js

nav:
  - Home: index.md
  - Investments:
      - Overview: investments/index.md
      - Boringdon Villas: investments/boringdon-villas/index.md
